
(function(){
const KEY='bdk-bia-cart-v3';
const read=()=>{try{return JSON.parse(localStorage.getItem(KEY)||'[]')}catch{return[]}};
const write=v=>{localStorage.setItem(KEY,JSON.stringify(v));renderCount();renderCart()};
const renderCount=()=>{const n=read().reduce((s,i)=>s+Number(i.qty||1),0);document.querySelectorAll('#cart-count').forEach(e=>e.textContent=n);const l=document.querySelector('#cart-count-large');if(l)l.textContent=n};
const add=item=>{const c=read();const f=c.find(x=>x.id===item.id && x.color===item.color && x.size===item.size);if(f)f.qty+=item.qty;else c.push(item);write(c)};
function renderCart(){const host=document.querySelector('[data-cart-items]');if(!host)return;const c=read();if(!c.length){host.innerHTML='<div class="empty">Seu carrinho está vazio.</div>';return}host.innerHTML=c.map((i,idx)=>'<div class="cart-item"><img src="'+i.image+'" alt=""><div><strong>'+i.name+'</strong><div>'+i.price+'</div><small>Cor: '+(i.color||'—')+' · Tamanho: '+(i.size||'—')+' · Quantidade: '+i.qty+'</small></div><button class="remove" data-remove="'+idx+'" type="button">Remover</button></div>').join('');host.querySelectorAll('[data-remove]').forEach(b=>b.addEventListener('click',()=>{const n=read();n.splice(Number(b.dataset.remove),1);write(n)}))}
function setupCarousel(){const root=document.querySelector('[data-carousel]');if(!root)return;const slides=[...root.querySelectorAll('.home-slide')],dots=[...root.querySelectorAll('.carousel-dot')];let i=0,timer;
const show=n=>{i=(n+slides.length)%slides.length;slides.forEach((s,k)=>s.classList.toggle('is-active',k===i));dots.forEach((d,k)=>d.classList.toggle('is-active',k===i))};
root.querySelector('.prev')?.addEventListener('click',()=>{show(i-1);restart()});root.querySelector('.next')?.addEventListener('click',()=>{show(i+1);restart()});dots.forEach((d,k)=>d.addEventListener('click',()=>{show(k);restart()}));
const start=()=>{timer=setInterval(()=>show(i+1),5500)},restart=()=>{clearInterval(timer);start()};show(0);start();
}
function setupPagination(){document.querySelectorAll('[data-pagination]').forEach(grid=>{const cards=[...grid.querySelectorAll(':scope > .product-card')];const size=8;if(cards.length<=size)return;const wrap=document.createElement('div');wrap.className='pagination';wrap.setAttribute('aria-label','Paginação de produtos');const pages=Math.ceil(cards.length/size);let page=0;
const render=()=>{cards.forEach((c,k)=>c.hidden=Math.floor(k/size)!==page);wrap.innerHTML='';const prev=document.createElement('button');prev.className='page-btn';prev.textContent='‹';prev.type='button';prev.disabled=page===0;prev.setAttribute('aria-label','Página anterior');prev.onclick=()=>{page--;render();window.scrollTo({top:grid.getBoundingClientRect().top+scrollY-120,behavior:'smooth'})};wrap.appendChild(prev);
for(let p=0;p<pages;p++){const b=document.createElement('button');b.type='button';b.className='page-btn'+(p===page?' is-active':'');b.textContent=p+1;b.setAttribute('aria-label','Página '+(p+1));b.setAttribute('aria-current',p===page?'page':'false');b.onclick=()=>{page=p;render();window.scrollTo({top:grid.getBoundingClientRect().top+scrollY-120,behavior:'smooth'})};wrap.appendChild(b)}
const next=document.createElement('button');next.className='page-btn';next.textContent='›';next.type='button';next.disabled=page===pages-1;next.setAttribute('aria-label','Próxima página');next.onclick=()=>{page++;render();window.scrollTo({top:grid.getBoundingClientRect().top+scrollY-120,behavior:'smooth'})};wrap.appendChild(next);
const status=document.createElement('span');status.className='page-status';status.textContent='Página '+(page+1)+' de '+pages;wrap.appendChild(status);grid.insertAdjacentElement('afterend',wrap)};render()})}
function setupProduct(){document.querySelectorAll('[data-product-detail]').forEach(d=>{
const colorHost=d.querySelector('[data-colors]');if(colorHost){colorHost.querySelectorAll('.swatch').forEach(b=>b.addEventListener('click',()=>{colorHost.querySelectorAll('.swatch').forEach(x=>x.classList.remove('is-selected'));b.classList.add('is-selected');d.dataset.color=b.dataset.value}))}
const size=d.querySelector('[name=size]');const qty=d.querySelector('[name=qty]');d.querySelector('[data-qty-minus]')?.addEventListener('click',()=>qty.value=Math.max(1,Number(qty.value||1)-1));d.querySelector('[data-qty-plus]')?.addEventListener('click',()=>qty.value=Math.min(99,Number(qty.value||1)+1));
d.querySelectorAll('[data-gallery-thumb]').forEach(t=>t.addEventListener('click',()=>{const main=d.querySelector('[data-gallery-main]');if(main){main.src=t.dataset.galleryThumb;d.querySelectorAll('[data-gallery-thumb]').forEach(x=>x.classList.remove('is-active'));t.classList.add('is-active')}}));
d.querySelector('.buy')?.addEventListener('click',()=>{const color=d.dataset.color||'';if(!color||!size?.value){alert('Selecione cor e tamanho antes de comprar.');return}add({id:d.dataset.id,name:d.dataset.name,price:d.dataset.price,image:d.dataset.image,qty:Math.max(1,Number(qty?.value||1)),color,size:size.value});const b=d.querySelector('.buy');b.classList.add('is-added');b.textContent='Adicionado ao carrinho';setTimeout(()=>{b.classList.remove('is-added');b.textContent='Comprar'},1300)});
})}
function setupWishlist(){document.querySelectorAll('[data-wishlist]').forEach(b=>b.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();b.classList.toggle('is-active');b.textContent=b.classList.contains('is-active')?'♥':'♡'}))}
function setupSearch(){const search=document.querySelector('[data-search]');if(!search)return;const cards=[...document.querySelectorAll('[data-product]')];const apply=()=>{const q=search.value.toLowerCase().trim();let shown=0;cards.forEach(c=>{const ok=!q||c.dataset.name.includes(q);c.hidden=!ok;if(ok)shown++});const empty=document.querySelector('[data-search-empty]');if(empty)empty.hidden=shown!==0};search.addEventListener('input',apply)}
function setupFilters(){const filters=[...document.querySelectorAll('[data-filter]')];if(!filters.length)return;const cards=[...document.querySelectorAll('[data-product]')];const apply=()=>{const cat=document.querySelector('[data-filter=category]')?.value||'all';const max=Number(document.querySelector('[data-filter=price]')?.value||0);cards.forEach(c=>{c.hidden=!((cat==='all'||c.dataset.category===cat)&&(!max||Number(c.dataset.price)<=max))})};filters.forEach(f=>f.addEventListener('change',apply))}
document.addEventListener('DOMContentLoaded',()=>{renderCount();renderCart();setupCarousel();setupPagination();setupProduct();setupWishlist();setupSearch();setupFilters()});
})();
