(function(){
const KEY='bdk-bia-cart-v4';
const read=()=>{try{return JSON.parse(localStorage.getItem(KEY)||'[]')}catch{return[]}};
const write=v=>{localStorage.setItem(KEY,JSON.stringify(v));renderCount();renderCart()};
const renderCount=()=>{const n=read().reduce((s,i)=>s+Number(i.qty||1),0);document.querySelectorAll('#cart-count,#cart-count-large').forEach(e=>e.textContent=n)};
const add=item=>{const c=read();const f=c.find(x=>x.id===item.id&&x.color===item.color&&x.size===item.size);if(f)f.qty+=item.qty;else c.push(item);write(c)};
function renderCart(){const host=document.querySelector('[data-cart-items]');if(!host)return;const c=read();if(!c.length){host.innerHTML='<div class="empty">Seu carrinho está vazio.</div>';return}host.innerHTML=c.map((i,idx)=>`<div class="cart-item"><img src="${i.image||''}" alt=""><div><strong>${i.name||'Produto'}</strong><div>${i.price||''}</div><small>Cor: ${i.color||'—'} · Tamanho: ${i.size||'—'} · Quantidade: ${i.qty||1}</small></div><button class="remove" data-remove="${idx}" type="button">Remover</button></div>`).join('');host.querySelectorAll('[data-remove]').forEach(b=>b.addEventListener('click',()=>{const n=read();n.splice(Number(b.dataset.remove),1);write(n)}))}
function qty(root){const q=root.querySelector('[data-qty],input[name=qty]');if(!q)return;const norm=()=>{let n=Number(q.value||1);if(!Number.isFinite(n))n=1;q.value=String(Math.min(99,Math.max(1,Math.round(n))))};root.querySelector('[data-minus], [data-qty-minus]')?.addEventListener('click',()=>{norm();q.value=String(Math.max(1,Number(q.value)-1))});root.querySelector('[data-plus], [data-qty-plus]')?.addEventListener('click',()=>{norm();q.value=String(Math.min(99,Number(q.value)+1))});q.addEventListener('blur',norm)}
function quick(){document.querySelectorAll('[data-quick]').forEach(card=>{let color='Coral',size='M';const main=card.querySelector('[data-main]');card.querySelectorAll('.thumb').forEach(t=>t.addEventListener('click',()=>{color=t.dataset.color;main.src=t.dataset.img;card.querySelector('[data-color-label]').textContent=color;card.querySelectorAll('.thumb').forEach(x=>x.classList.toggle('active',x===t))}));card.querySelectorAll('.size').forEach(s=>s.addEventListener('click',()=>{size=s.dataset.size;card.querySelectorAll('.size').forEach(x=>x.classList.toggle('active',x===s))}));qty(card);card.querySelector('[data-buy]')?.addEventListener('click',()=>{const q=card.querySelector('[data-qty]');const n=Math.min(99,Math.max(1,Number(q.value||1)));q.value=String(n);add({id:card.dataset.id,name:card.dataset.name,price:'R$ '+Number(card.dataset.price).toFixed(2).replace('.',','),image:main.currentSrc||main.src,qty:n,color,size});const b=card.querySelector('[data-buy]');b.classList.add('added');b.textContent='Adicionado ao carrinho';setTimeout(()=>{b.classList.remove('added');b.textContent='Comprar agora'},1200)})})}
function oldProduct(){document.querySelectorAll('[data-product-detail]').forEach(d=>{let color=d.dataset.color||'Coral';const size=d.querySelector('[name=size]');qty(d);d.querySelectorAll('[data-color]').forEach(b=>b.addEventListener('click',()=>{color=b.dataset.color;d.querySelector('[data-selected-color]').textContent=color;d.querySelectorAll('[data-color]').forEach(x=>x.classList.toggle('is-selected',x===b))}));d.querySelector('.buy')?.addEventListener('click',()=>{if(!size?.value)return alert('Selecione o tamanho antes de comprar.');const q=d.querySelector('[name=qty]');add({id:d.dataset.id,name:d.dataset.name,price:d.dataset.price,image:d.dataset.image,qty:Number(q?.value||1),color,size:size.value});})})}
function search(){const s=document.querySelector('[data-search]');if(!s)return;const cards=[...document.querySelectorAll('.product-card')];s.addEventListener('input',()=>{const q=s.value.toLowerCase().trim();cards.forEach(c=>c.hidden=!!q&&!c.textContent.toLowerCase().includes(q))})}
document.addEventListener('DOMContentLoaded',()=>{renderCount();renderCart();quick();oldProduct();search()});
})();