const CART_KEY='bdk-bia-mvp-v3-cart';
const PRODUCTS=[
{name:'Cortininha + Asa Delta',price:164.9,url:'produto/biquini-cortininha-e-calcinha-asa-delta.html',image:'https://images.unsplash.com/photo-1566447172003-b861a3a44ae7?auto=format&fit=crop&q=88&w=1200',category:'biquini'},
{name:'Maggie + Fio Regulável',price:219.9,url:'produto/biquini-maggie-e-calcinha-fio-regulavel.html',image:'https://images.unsplash.com/photo-1778754821906-789523631d40?auto=format&fit=crop&q=88&w=1200',category:'biquini'},
{name:'Cortininha + Fio',price:149.9,url:'produto/biquini-cortininha-e-calcinha-fio.html',image:'https://images.unsplash.com/photo-1638389882545-d414e82ba876?auto=format&fit=crop&q=88&w=1200',category:'biquini'},
{name:'Cortininha + Laço',price:99.9,url:'produto/biquini-cortininha-e-calcinha-laco.html',image:'https://images.unsplash.com/photo-1638389882545-d414e82ba876?auto=format&fit=crop&q=88&w=1200',category:'biquini'},
{name:'Barbatana + Asa Delta',price:144.9,url:'produto/biquini-barbatana-e-asa-delta-fio-duplo.html',image:'https://images.unsplash.com/photo-1566447172003-b861a3a44ae7?auto=format&fit=crop&q=88&w=1200',category:'biquini'},
{name:'Louise + Fio Duplo',price:209.9,url:'produto/biquini-louise-e-calcinha-fio-duplo.html',image:'https://images.unsplash.com/photo-1778754821906-789523631d40?auto=format&fit=crop&q=88&w=1200',category:'biquini'},
{name:'Maiô Decote Profundo',price:194.9,url:'produto/maio-decote-profundo.html',image:'https://images.unsplash.com/photo-1698204625359-b64409e5a942?auto=format&fit=crop&q=88&w=1200',category:'maio'}
];
const money=n=>'R$ '+Number(n).toFixed(2).replace('.',',');
function getCart(){try{return JSON.parse(localStorage.getItem(CART_KEY)||'[]')}catch{return[]}}
function saveCart(c){localStorage.setItem(CART_KEY,JSON.stringify(c));renderCount();renderCart()}
function renderCount(){const n=getCart().reduce((s,i)=>s+Number(i.qty||1),0);document.querySelectorAll('[data-cart-count],#cart-count,#count').forEach(e=>e.textContent=n)}
function addToCart(item){const c=getCart();const id=item.id||item.name;const found=c.find(x=>x.id===id&&x.color===(item.color||'')&&x.size===(item.size||''));if(found)found.qty+=Number(item.qty||1);else c.push({...item,id,qty:Number(item.qty||1)});saveCart(c)}
function bindBuyButtons(){document.querySelectorAll('[data-buy],[data-add]').forEach(btn=>{if(btn.dataset.bound)return;btn.dataset.bound='1';btn.addEventListener('click',()=>{let item;if(btn.dataset.add!==undefined){item=PRODUCTS[Number(btn.dataset.add)];if(!item)return;item={id:item.name,name:item.name,price:item.price,image:item.image,color:'Preto',size:'M',qty:1}}else{const card=btn.closest('[data-product]');if(!card)return;const d=card.dataset;item={id:d.id,name:d.name,price:Number(d.price),image:d.image,color:'Preto',size:'M',qty:1}}addToCart(item);btn.textContent='Adicionado ✓';btn.classList.add('added');setTimeout(()=>{btn.textContent='Adicionar à sacola';btn.classList.remove('added')},1200)})})}
function bindMobileNav(){const trigger=document.querySelector('[data-menu],#menu'),nav=document.querySelector('[data-mobile-nav],#mobileNav');trigger?.addEventListener('click',()=>nav?.classList.toggle('open'))}
function bindSearch(){const drawer=document.querySelector('[data-search-drawer]');if(!drawer)return;document.querySelectorAll('[data-search-open]').forEach(b=>b.addEventListener('click',()=>{drawer.classList.add('open');setTimeout(()=>drawer.querySelector('[data-search-input]')?.focus(),120)}));drawer.querySelector('[data-search-close]')?.addEventListener('click',()=>drawer.classList.remove('open'));const input=drawer.querySelector('[data-search-input]'),out=drawer.querySelector('[data-search-results]');input?.addEventListener('input',()=>{const q=input.value.trim().toLowerCase();if(!q){out.innerHTML='';return}const hits=PRODUCTS.filter(p=>p.name.toLowerCase().includes(q));out.innerHTML=hits.length?hits.map(p=>`<a class="search-result" href="${p.url}"><span>${p.name}</span><small>${money(p.price)}</small></a>`).join(''):'<p class="empty">Nenhum resultado.</p>'})}
function bindPdp(){const root=document.querySelector('[data-pdp]');if(!root)return;let color='Preto';let size='';const q=root.querySelector('[data-qty]');root.querySelectorAll('[data-color]').forEach(b=>b.addEventListener('click',()=>{color=b.dataset.color;root.querySelector('[data-selected-color]').textContent=color;root.querySelectorAll('[data-color]').forEach(x=>x.classList.toggle('active',x===b))}));root.querySelectorAll('[data-size]').forEach(b=>b.addEventListener('click',()=>{size=b.dataset.size;root.querySelector('[data-selected-size]').textContent=size;root.querySelectorAll('[data-size]').forEach(x=>x.classList.toggle('active',x===b))}));root.querySelector('[data-minus]')?.addEventListener('click',()=>q.value=String(Math.max(1,Number(q.value||1)-1)));root.querySelector('[data-plus]')?.addEventListener('click',()=>q.value=String(Math.min(99,Number(q.value||1)+1)));root.querySelector('[data-pdp-buy]')?.addEventListener('click',()=>{if(!size){alert('Selecione um tamanho para continuar.');return}const b=root.querySelector('[data-pdp-buy]');addToCart({id:root.dataset.id,name:root.dataset.name,price:Number(root.dataset.price),image:root.dataset.image,color,size,qty:Number(q.value||1)});b.textContent='Adicionado à sacola ✓';b.classList.add('added');setTimeout(()=>{b.textContent='Adicionar à sacola';b.classList.remove('added')},1200)})}
function bindFilters(){const grid=document.querySelector('[data-catalog-grid]');if(!grid)return;const cards=[...grid.querySelectorAll('[data-product]')],category=document.querySelector('[data-filter-category]'),price=document.querySelector('[data-filter-price]');const apply=()=>{const cat=category?.value||'all',max=Number(price?.value||0);cards.forEach(c=>{const okCat=cat==='all'||c.dataset.category===cat;const okPrice=!max||Number(c.dataset.price)<=max;c.hidden=!(okCat&&okPrice)})};category?.addEventListener('change',apply);price?.addEventListener('change',apply);apply()}
function renderCart(){const host=document.querySelector('[data-cart],#cart');if(!host)return;const c=getCart();if(!c.length){host.innerHTML='<div class="empty"><p>Sua sacola está vazia.</p><a class="text-link" href="index.html">Voltar para a loja →</a></div>';return}const subtotal=c.reduce((s,i)=>s+Number(i.price)*Number(i.qty||1),0);host.innerHTML=`<div class="cart-items">${c.map((i,idx)=>`<div class="cart-item"><img src="${i.image||''}" alt=""><div><h3>${i.name}</h3><small>${money(i.price)} · Cor: ${i.color||'—'} · Tamanho: ${i.size||'—'} · Qtd. ${i.qty||1}</small></div><button class="remove" data-remove="${idx}">Remover</button></div>`).join('')}</div><div class="cart-summary"><div class="summary-box"><div class="summary-line"><span>Subtotal</span><strong>${money(subtotal)}</strong></div><div class="summary-line"><span>Pix (5% OFF)</span><strong>${money(subtotal*.95)}</strong></div><button class="checkout" data-checkout>Simular checkout</button></div></div>`;host.querySelectorAll('[data-remove]').forEach(b=>b.addEventListener('click',()=>{const next=getCart();next.splice(Number(b.dataset.remove),1);saveCart(next)}));host.querySelector('[data-checkout]')?.addEventListener('click',()=>alert('Checkout demonstrativo: nenhum pagamento real é processado.'))}
function init(){renderCount();bindBuyButtons();bindMobileNav();bindSearch();bindPdp();bindFilters();renderCart()}
document.addEventListener('DOMContentLoaded',init);